name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # 当你推送 v1.0.0 这种标签时触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # 授权获取 OIDC 临时令牌
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1